DROP TABLE USERS CASCADE;
DROP TABLE TRANSACTIONS CASCADE;
DROP TABLE SIGGROUPS CASCADE;
DROP TABLE EVENTS CASCADE;
DROP TABLE ORGANIZERS CASCADE;
DROP TABLE COMPANIES CASCADE;
DROP TABLE USERS_EVENTS CASCADE;
DROP TABLE USERS_SIGGROUPS CASCADE;
DROP TABLE USERS_SESSIONS CASCADE;


CREATE TABLE USERS
(
  UID SERIAL PRIMARY KEY,
  firstName VARCHAR(30),
  lastName VARCHAR(40),
  email VARCHAR(50) UNIQUE NOT NULL,
  phone VARCHAR(15),
  username VARCHAR(20) UNIQUE NOT NULL,
  password VARCHAR(60),
  salt VARCHAR(60),
  accountCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP(0),
  accountExpires TIMESTAMP DEFAULT (CURRENT_TIMESTAMP(0) + INTERVAL '1 YEAR'),
  userlevel INTEGER DEFAULT 0
);

CREATE TABLE USERS_SESSIONS
(
  UID INTEGER PRIMARY KEY,
  HASH VARCHAR(60),
  FOREIGN KEY (UID) REFERENCES USERS ON DELETE CASCADE
);

CREATE TABLE TRANSACTIONS
(
  TID SERIAL,
  AMOUNT NUMERIC(6, 2),
  DESCRIPTION VARCHAR(100),
  TIME_INITIATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP(0),
  UID INTEGER,
  PRIMARY KEY (TID),
  FOREIGN KEY (UID) REFERENCES USERS ON DELETE CASCADE
);

CREATE TABLE ORGANIZERS
(
  OID SERIAL,
  title VARCHAR(40) UNIQUE NOT NULL,
  PRIMARY KEY (OID)
);

CREATE TABLE SIGGROUPS
(
  GID SERIAL, 
  DESCRIPTION TEXT,
  LEADER_ID INTEGER REFERENCES USERS(UID) ON DELETE SET NULL,
  MEETING_DAY VARCHAR(10),
  MEETING_TIME TIME,
  OID INTEGER NOT NULL,
  PRIMARY KEY (GID),
  FOREIGN KEY (OID) REFERENCES ORGANIZERS ON DELETE CASCADE
);

CREATE TABLE USERS_SIGGROUPS
(
  JID SERIAL,
  UID INTEGER REFERENCES USERS ON DELETE CASCADE NOT NULL,
  GID INTEGER REFERENCES SIGGROUPS ON DELETE CASCADE NOT NULL,
  joinedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP(0),
  PRIMARY KEY(JID),
  UNIQUE(UID,GID)
);

CREATE TABLE COMPANIES
(
  CID SERIAL,
  CONTACT_PERSON VARCHAR(40),
  CONTACT_PHONE VARCHAR(20),
  CONTACT_EMAIL VARCHAR(40),
  OID INTEGER NOT NULL,
  PRIMARY KEY (CID),
  FOREIGN KEY (OID) REFERENCES ORGANIZERS ON DELETE CASCADE
);

CREATE TABLE EVENTS
(
  EID SERIAL,
  EVENT_NAME VARCHAR(30),
  LOCATION VARCHAR(20),
  EVENT_DATETIME TIMESTAMP,
  OID INTEGER,
  PRIMARY KEY (EID),
  FOREIGN KEY (OID) REFERENCES ORGANIZERS ON DELETE CASCADE
);

CREATE TABLE USERS_EVENTS
(
  PID SERIAL,
  UID INTEGER REFERENCES USERS ON DELETE CASCADE NOT NULL,
  EID INTEGER REFERENCES EVENTS ON DELETE CASCADE NOT NULL,
  PRIMARY KEY (PID),
  UNIQUE(UID, EID)
);
